<a href="https://colab.research.google.com/github/vaila-street/py-test/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
x=pd.read_csv('DTS_1.csv')

In [4]:
x

,DTS File ID,Part ID,Cat ID,File Def Id,File Name,File Size,File Source,User ID,File Ack'd,Ack File ID,...,Msg Id,# Wrngs,# Excpts,# Resends,Is Dup,Has Dup,Sub Flow,attrib_0_val,attrib_8_val,attrib_9_val
0,779996408,202204,1,9001425,V16026036.usr,3516,IN_E_DTN,NaN,0,0,...,0,0,0,0,False,False,NaN,NaN,NaN,NaN
1,779996383,202204,1,9001425,V16026052.usr,1210,IN_E_DTN,NaN,0,0,...,0,0,0,0,False,False,NaN,NaN,NaN,NaN
2,779962399,202204,1,9001425,V16024688.usr,3206,IN_E_DTN,NaN,0,0,...,0,0,0,0,False,False,NaN,NaN,NaN,NaN
3,779962395,202204,1,9001425,V16024691.usr,1022,IN_E_DTN,NaN,0,0,...,0,0,0,0,False,False,NaN,NaN,NaN,NaN
4,779932984,202204,1,9001425,XSPOW62779.conv.INT.MPMAMS,3088,IN_E_IBSP_MPRS_MANW,NaN,0,0,...,0,0,0,0,False,False,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,778883564,202204,1,9001425,V15926277.usr,4068,IN_E_DTN,NaN,0,0,...,0,0,0,0,False,False,NaN,NaN,NaN,NaN
155,778773439,202204,1,9001425,XSPOW62703.conv.INT.MPMAMS,989,IN_E_IBSP_MPRS_MANW,NaN,0,0,...,0,0,0,0,False,False,NaN,NaN,NaN,NaN
156,778773438,202204,1,9001425,XSPOW62707.conv.INT.MPMAMS,2558,IN_E_IBSP_MPRS_MANW,NaN,0,0,...,0,0,0,0,False,False,NaN,NaN,NaN,NaN
157,778773394,202204,1,9001425,XSPOW90601.conv.INT.MPSAMS,2091,IN_E_IBSP_MPRS_SPOW,NaN,0,0,...,0,0,0,0,False,False,NaN,NaN,NaN,NaN
158,778773391,202204,1,9001425,XSPOW90607.conv.INT.MPSAMS,5422,IN_E_IBSP_MPRS_SPOW,NaN,0,0,...,0,0,0,0,False,False,NaN,NaN,NaN,NaN

In [16]:
dtn = x['File Source']

In [18]:
dtn1= x.iloc[:,5]

In [19]:
print (dtn1)

0      3516
1      1210
2      3206
3      1022
4      3088
       ...
154    4068
155     989
156    2558
157    2091
158    5422
Name: File Size, Length: 159, dtype: int64

In [17]:
print(dtn)

0      IN_E_DTN
1      IN_E_DTN
2      IN_E_DTN
3      IN_E_DTN
4      IN_E_DTN
         ...
154    IN_E_DTN
155    IN_E_DTN
156    IN_E_DTN
157    IN_E_DTN
158    IN_E_DTN
Name: File Source, Length: 159, dtype: object